# Лабораторная работа №2

## Баканов Сергей ИБМ3-65Б

In [29]:
import numpy as np
import pandas as pd
from sklearn.datasets import *
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
data = pd.read_csv("languages.csv", encoding = 'utf-8')
data.head()

,pldb_id,title,description,type,appeared,creators,website,domain_name,domain_name_registered,reference,...,features_has_semantic_indentation,features_has_line_comments,line_comment_token,last_activity,number_of_users,number_of_jobs,origin_community,central_package_repository_count,file_type,is_open_source
0,java,Java,NaN,pl,1995,James Gosling,https://oracle.com/java/,NaN,NaN,NaN,...,False,True,//,2022,5550123,85206,Sun Microsystems,NaN,text,NaN
1,javascript,JavaScript,NaN,pl,1995,Brendan Eich,NaN,NaN,NaN,https://www.w3schools.com/js/js_reserved.asp,...,False,True,//,2022,5962666,63993,Netscape,NaN,text,NaN
2,c,C,NaN,pl,1972,Dennis Ritchie,NaN,NaN,NaN,http://www.c4learn.com/c-programming/c-keywords/,...,False,True,//,2022,3793768,59919,Bell Labs,0.0,text,NaN
3,python,Python,NaN,pl,1991,Guido van Rossum,https://www.python.org/,python.org,1995.0,https://www.programiz.com/python-programming/k...,...,True,True,#,2022,2818037,46976,Centrum Wiskunde & Informatica,NaN,text,NaN
4,sql,SQL,NaN,queryLanguage,1974,Donald D. Chamberlin and Raymond F. Boyce,NaN,NaN,NaN,NaN,...,False,True,--,2022,7179119,219617,IBM,0.0,text,NaN

In [31]:
data.shape

(4303, 49)

In [32]:
data.describe()

,appeared,domain_name_registered,isbndb,book_count,semantic_scholar,language_rank,github_repo_stars,github_repo_forks,github_repo_updated,github_repo_subscribers,...,wikipedia_daily_page_views,wikipedia_backlinks_count,wikipedia_page_id,wikipedia_appeared,wikipedia_created,wikipedia_revision_count,last_activity,number_of_users,number_of_jobs,central_package_repository_count
count,4303.000000,502.000000,1086.000000,4303.000000,758.000000,4303.000000,889.000000,886.000000,885.000000,885.000000,...,1466.000000,1426.000000,1.410000e+03,1345.000000,1263.000000,1173.000000,4303.000000,4.303000e+03,4303.000000,2821.0
mean,1991.105275,2011.332669,7.706262,2.079479,3.794195,2151.000000,2127.402700,261.286682,2021.389831,62.342373,...,227.133015,318.548387,9.167847e+06,1991.144238,2005.748219,330.431373,2000.616082,1.377126e+04,422.183825,0.0
std,111.443382,7.021132,33.164209,17.344654,8.316231,1242.313433,7554.016422,1203.002760,1.763285,200.882012,...,783.552400,1635.289188,1.350683e+07,17.026503,3.768240,813.255594,84.597760,2.277129e+05,12572.985441,0.0
min,-2000.000000,1990.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2012.000000,0.000000,...,-1.000000,1.000000,9.280000e+02,1830.000000,2001.000000,1.000000,-900.000000,0.000000e+00,0.000000,0.0
25%,1984.000000,2007.000000,0.000000,0.000000,0.000000,1075.500000,29.000000,2.250000,2022.000000,4.000000,...,9.000000,13.000000,3.751538e+05,1980.000000,2003.000000,35.000000,1992.000000,0.000000e+00,0.000000,0.0
50%,1997.000000,2013.000000,0.000000,0.000000,0.000000,2151.000000,194.000000,16.000000,2022.000000,13.000000,...,24.000000,39.000000,2.114700e+06,1994.000000,2005.000000,84.000000,2006.000000,2.000000e+01,0.000000,0.0
75%,2012.000000,2017.000000,2.000000,0.000000,3.000000,3226.500000,1071.000000,91.500000,2022.000000,44.000000,...,99.000000,126.000000,1.232122e+07,2005.000000,2007.000000,242.000000,2021.000000,2.300000e+02,0.000000,0.0
max,2023.000000,2023.000000,400.000000,401.000000,52.000000,4302.000000,88526.000000,23732.000000,2023.000000,2910.000000,...,13394.000000,34348.000000,6.306355e+07,2019.000000,2020.000000,10104.000000,2023.000000,7.179119e+06,771996.000000,0.0

In [33]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4303 entries, 0 to 4302
Data columns (total 49 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   pldb_id                            4303 non-null   str
 1   title                              4303 non-null   str
 2   description                        823 non-null    str
 3   type                               4303 non-null   str
 4   appeared                           4303 non-null   int64
 5   creators                           1100 non-null   str
 6   website                            1375 non-null   str
 7   domain_name                        715 non-null    str
 8   domain_name_registered             502 non-null    float64
 9   reference                          1989 non-null   str
 10  isbndb                             1086 non-null   float64
 11  book_count                         4303 non-null   int64
 12  semantic_scholar                   758 non-null    float64
 13  language_rank                      4303 non-null   int64
 14  github_repo                        901 non-null    str
 15  github_repo_stars                  889 non-null    float64
 16  github_repo_forks                  886 non-null    float64
 17  github_repo_updated                885 non-null    float64
 18  github_repo_subscribers            885 non-null    float64
 19  github_repo_created                878 non-null    float64
 20  github_repo_description            865 non-null    str
 21  github_repo_issues                 785 non-null    float64
 22  github_repo_first_commit           736 non-null    float64
 23  github_language                    474 non-null    str
 24  github_language_tm_scope           466 non-null    str
 25  github_language_type               466 non-null    str
 26  github_language_ace_mode           465 non-null    str
 27  github_language_file_extensions    470 non-null    str
 28  github_language_repos              470 non-null    float64
 29  wikipedia                          1572 non-null   str
 30  wikipedia_daily_page_views         1466 non-null   float64
 31  wikipedia_backlinks_count          1426 non-null   float64
 32  wikipedia_summary                  1419 non-null   str
 33  wikipedia_page_id                  1410 non-null   float64
 34  wikipedia_appeared                 1345 non-null   float64
 35  wikipedia_created                  1263 non-null   float64
 36  wikipedia_revision_count           1173 non-null   float64
 37  wikipedia_related                  1158 non-null   str
 38  features_has_comments              620 non-null    object
 39  features_has_semantic_indentation  581 non-null    object
 40  features_has_line_comments         538 non-null    object
 41  line_comment_token                 472 non-null    str
 42  last_activity                      4303 non-null   int64
 43  number_of_users                    4303 non-null   int64
 44  number_of_jobs                     4303 non-null   int64
 45  origin_community                   3113 non-null   str
 46  central_package_repository_count   2821 non-null   float64
 47  file_type                          1090 non-null   str
 48  is_open_source                     511 non-null    object
dtypes: float64(18), int64(6), object(4), str(21)
memory usage: 1.6+ MB

In [34]:
data.isna().sum()

pldb_id                                 0
title                                   0
description                          3480
type                                    0
appeared                                0
creators                             3203
website                              2928
domain_name                          3588
domain_name_registered               3801
reference                            2314
isbndb                               3217
book_count                              0
semantic_scholar                     3545
language_rank                           0
github_repo                          3402
github_repo_stars                    3414
github_repo_forks                    3417
github_repo_updated                  3418
github_repo_subscribers              3418
github_repo_created                  3425
github_repo_description              3438
github_repo_issues                   3518
github_repo_first_commit             3567
github_language                      3829
github_language_tm_scope             3837
github_language_type                 3837
github_language_ace_mode             3838
github_language_file_extensions      3833
github_language_repos                3833
wikipedia                            2731
wikipedia_daily_page_views           2837
wikipedia_backlinks_count            2877
wikipedia_summary                    2884
wikipedia_page_id                    2893
wikipedia_appeared                   2958
wikipedia_created                    3040
wikipedia_revision_count             3130
wikipedia_related                    3145
features_has_comments                3683
features_has_semantic_indentation    3722
features_has_line_comments           3765
line_comment_token                   3831
last_activity                           0
number_of_users                         0
number_of_jobs                          0
origin_community                     1190
central_package_repository_count     1482
file_type                            3213
is_open_source                       3792
dtype: int64

In [35]:
data = data.drop(columns=data.columns[data.isna().sum() >= 3000])

In [36]:
data.isna().sum()

pldb_id                                0
title                                  0
type                                   0
appeared                               0
website                             2928
reference                           2314
book_count                             0
language_rank                          0
wikipedia                           2731
wikipedia_daily_page_views          2837
wikipedia_backlinks_count           2877
wikipedia_summary                   2884
wikipedia_page_id                   2893
wikipedia_appeared                  2958
last_activity                          0
number_of_users                        0
number_of_jobs                         0
origin_community                    1190
central_package_repository_count    1482
dtype: int64

In [37]:
data = data.drop(["website", "reference", "wikipedia", "wikipedia_page_id", "wikipedia_appeared", "wikipedia_summary", "origin_community"], axis = 1)

In [38]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4303 entries, 0 to 4302
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pldb_id                           4303 non-null   str
 1   title                             4303 non-null   str
 2   type                              4303 non-null   str
 3   appeared                          4303 non-null   int64
 4   book_count                        4303 non-null   int64
 5   language_rank                     4303 non-null   int64
 6   wikipedia_daily_page_views        1466 non-null   float64
 7   wikipedia_backlinks_count         1426 non-null   float64
 8   last_activity                     4303 non-null   int64
 9   number_of_users                   4303 non-null   int64
 10  number_of_jobs                    4303 non-null   int64
 11  central_package_repository_count  2821 non-null   float64
dtypes: float64(3), int64(6), str(3)
memory usage: 403.5 KB

In [39]:
mode_value = data['central_package_repository_count'].mode()[0]
data['central_package_repository_count'] = data['central_package_repository_count'].fillna(mode_value)

mean_value = data['wikipedia_daily_page_views'].mean()
data['wikipedia_daily_page_views'] = data['wikipedia_daily_page_views'].fillna(mean_value)

mean_value = data['wikipedia_backlinks_count'].mean()
data['wikipedia_backlinks_count'] = data['wikipedia_backlinks_count'].fillna(mean_value)

In [40]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4303 entries, 0 to 4302
Data columns (total 12 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   pldb_id                           4303 non-null   str
 1   title                             4303 non-null   str
 2   type                              4303 non-null   str
 3   appeared                          4303 non-null   int64
 4   book_count                        4303 non-null   int64
 5   language_rank                     4303 non-null   int64
 6   wikipedia_daily_page_views        4303 non-null   float64
 7   wikipedia_backlinks_count         4303 non-null   float64
 8   last_activity                     4303 non-null   int64
 9   number_of_users                   4303 non-null   int64
 10  number_of_jobs                    4303 non-null   int64
 11  central_package_repository_count  4303 non-null   float64
dtypes: float64(3), int64(6), str(3)
memory usage: 403.5 KB

In [41]:
data = data.drop(["pldb_id", "title"], axis = 1)

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['type_code'] = le.fit_transform(data['type'])
data = data.drop("type", axis = 1)

In [43]:
numeric_cols = data.columns

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

In [44]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4303 entries, 0 to 4302
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   appeared                          4303 non-null   float64
 1   book_count                        4303 non-null   float64
 2   language_rank                     4303 non-null   float64
 3   wikipedia_daily_page_views        4303 non-null   float64
 4   wikipedia_backlinks_count         4303 non-null   float64
 5   last_activity                     4303 non-null   float64
 6   number_of_users                   4303 non-null   float64
 7   number_of_jobs                    4303 non-null   float64
 8   central_package_repository_count  4303 non-null   float64
 9   type_code                         4303 non-null   float64
dtypes: float64(10)
memory usage: 336.3 KB